### PR TITLE
changed app.io to _this on emits

### LINKED ISSUE #369: Improper use of app.io.emit
If I understand correctly, `app.io.emit` sends a broadcast to *all* socket listeners, whereas `this.socket.emit` only sends the message to the calling connection.

In many places in the code, `app.io.emit` appears to be used where `this.emit` would be a better fit.

### PR DESCRIPTION
**Pull request by stevethomas19**
To fix #369

### CODE REVIEW

**Comment by webnard** [comment]
Not all of these will need to be changed. For example, the calendar probably benefits from having a broadcast, as it can update in real-time across the board for anyone who is looking at the calendar. Thoughts, @alexcdahl?

**Comment by stevethomas19** [comment]
K no worries. Easy thing to revert. Just give me the list of situations that will be okay to broadcast and I'll fix things up.

**Comment by trevren11** [comment]
Things that should have event broadcast to everyone:
Calendar events
Messages (and everything in the file)

Things that should not
Check in
View history

Correct me if I am wrong but those should be what you need.

**Comment by stevethomas19** [comment]
That sounds good to me. If everyone else is good with that decision, I will implement it on Monday.

**Comment by trevren11** [comment]
@stevethomas19 tsk tsk tsk Steven, it seems to be Tuesday and nothing.... hahaha jk. Not like you have 9 other requests pending for merge or anything.

**Comment by stevethomas19** [comment]
@trevren11 what do you mean? I made the changes. Did they not get pushed?

**Comment by trevren11** [comment]
@stevethomas19 I was looking at the Files Changed but I forgot they don't always show what is on the branch. I had to go to your other commit, sorry haha.

**Pull request merged**
