### PR TITLE
added media type column to checkin table

### PR DESCRIPTION
**Pull request by stevethomas19**

### CODE REVIEW

**Comment by webnard** [comment]
Looks like the push build failure may have been a fluke. I'm restarting it and expect everything will work okay. Once it does, feel free to merge.

**Comment by alexcdahl** [comment]
Oh good, it passed. It looks good. The only critique I have is that it would be good if instead of displaying 'null' if it maybe were just blank or something.

**Comment by stevethomas19** [comment]
I need to adjust where it is located in the table and I'll display a blank string rather than null, though Harold said it should never be null.

**Comment by alexcdahl** [comment]
Looks good to me. @webnard, any input before merging?

**Comment by webnard** [comment]
lgtm

**Pull request merged**
