### PR TITLE
Postgres passwords allow for special characters.

### PR DESCRIPTION
**Pull request by webnard**

### CODE REVIEW

**Comment by alexcdahl** [comment]
So the build failed on this... that means it shouldn't be merged in, right?

**Comment by Luke1298** [comment]
Those Errors.... They are the cursed error. Identical to those of the
ancient days when I was on this project.

**Comment by webnard** [comment]
Yeah—those errors are related to connecting to the database, so this PR did the opposite of what I wanted it to do. Reason for this is here: https://github.com/iceddev/pg-connection-string/pull/4

**Comment by webnard** [comment]
> So the build failed on this... that means it shouldn't be merged in, right?

Yeah. The pull request could still be useful, though, so let's leave it open, and if I have time I'll fix it.

**Pull request closed without merging**
