### PR TITLE
Fixes for editing the catalog. Finishes #299

### PR DESCRIPTION
**Pull request by webnard**
Ref. #299

### CODE REVIEW

**Comment by alexcdahl** [comment]
This looks good to me. Do you want to go ahead and pully it in?

**Comment by webnard** [comment]
Sure, that'd be great. Thanks!

On Tue, Jun 16, 2015 at 12:49 PM, Alexander Dahl <notifications@github.com>
wrote:

> This looks good to me. Do you want to go ahead and pully it in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/pull/307#issuecomment-112526677>.
>



-- 
 ian hunter

**Comment by alexcdahl** [comment]
No, I mean do *you* want to pully it in. I still don't know how to comfortably use pully-- too scared I'd break something.

**Comment by webnard** [comment]
Oh, yeah, sorry. Read an extra word in there.

On Tue, Jun 16, 2015 at 12:58 PM, Alexander Dahl <notifications@github.com>
wrote:

> No, I mean do *you* want to pully it in. I still don't know how to
> comfortably use pully-- too scared I'd break something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/pull/307#issuecomment-112528813>.
>



-- 
 ian hunter

**Pull request closed without merging**
