### PR TITLE
Lukedev6

### PR DESCRIPTION
**Pull request by Luke1298**

### CODE REVIEW

**Comment by Luke1298** [comment]
@webnard What think ye? Worthy of Master?

**Comment by webnard** [comment]
@Luke1298 -- looking over it now; sorry for the delay.

**Comment by Luke1298** [comment]
np

**Comment by webnard** [comment]
@Luke1298 -- I can view this page as a non-admin. Can you have it redirect to a 40X page instead? (401 or 403; I can't remember which is better suited for this.)

Otherwise, things look fine. I assume the delete button isn't supposed to work yet?

**Comment by Luke1298** [comment]
Delete page is to come. :D

**Pull request closed without merging**
